# Generated by Django 4.2.2 on 2023-06-09 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0002_alter_book_pub_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="pub_year",
            field=models.IntegerField(
                default=datetime.datetime(
                    2023, 6, 9, 16, 16, 15, 961676, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
